services:
    _defaults:
        public: false
        autowire: true

    Fontai\Bundle\ProxyBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Fontai\Bundle\ProxyBundle\Service\FileCache:
        arguments:
            - '@filesystem'
            - '%proxy.aliases%'
            - '%proxy.public_dir%'
            - '%kernel.cache_dir%/proxy'
            - '%proxy.source_maps%'